/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author angi0
 */
public class menuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuprincipal
     */
    public menuprincipal() {
        initComponents();
        txtidu.setVisible(false);  
        java.awt.EventQueue.invokeLater(() -> {
            checkUserType();
        });
    }

    
    private void checkUserType() {
        String usutipo = txttipo.getText().trim();  
        if (usutipo.equalsIgnoreCase("admin")) {   
            jMenu1.setVisible(true);                
        } else {
            jMenu1.setVisible(false);              
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusuario = new javax.swing.JLabel();
        txttipo = new javax.swing.JLabel();
        txtidu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuclientes = new javax.swing.JMenuItem();
        menupersinales = new javax.swing.JMenuItem();
        menuusuarios = new javax.swing.JMenuItem();
        menuproductos = new javax.swing.JMenuItem();
        PRESTAMO = new javax.swing.JMenu();
        menuventas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtusuario.setText("txtusuario");

        txttipo.setText("txttipo");

        txtidu.setText("jLabel1");

        jMenu1.setText("MANTENIMIENTO");

        menuclientes.setText("AUTORES");
        menuclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuclientesActionPerformed(evt);
            }
        });
        jMenu1.add(menuclientes);

        menupersinales.setText("PESRONAS");
        menupersinales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupersinalesActionPerformed(evt);
            }
        });
        jMenu1.add(menupersinales);

        menuusuarios.setText(" USUARIOS");
        jMenu1.add(menuusuarios);

        menuproductos.setText("LIBROS");
        jMenu1.add(menuproductos);

        jMenuBar1.add(jMenu1);

        PRESTAMO.setText("PRESTAMO");

        menuventas.setText("PRESTAMO");
        menuventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuventasActionPerformed(evt);
            }
        });
        PRESTAMO.add(menuventas);

        jMenuBar1.add(PRESTAMO);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuario)
                    .addComponent(txttipo)
                    .addComponent(txtidu))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menupersinalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupersinalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menupersinalesActionPerformed

    private void menuclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuclientesActionPerformed

    private void menuventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuventasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu PRESTAMO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem menuclientes;
    public javax.swing.JMenuItem menupersinales;
    public javax.swing.JMenuItem menuproductos;
    public javax.swing.JMenuItem menuusuarios;
    public javax.swing.JMenuItem menuventas;
    public javax.swing.JLabel txtidu;
    public javax.swing.JLabel txttipo;
    public javax.swing.JLabel txtusuario;
    // End of variables declaration//GEN-END:variables
}
